# docker run -d -p 1935:1935 -p 8080:8080 -v custom.conf:/etc/nginx/nginx.conf alqutami/rtmp-hls:latest-alpine

# docker-compose -f rtmp-alpine.yaml up
version: "3.5"

services:
  nginx-rtmp:
    image: alqutami/rtmp-hls:latest-alpine
    restart: always
    ports:
      - "1935:1935"
      - "8080:8080"
    volumes:
      - "./conf/nginx_no-ffmpeg.conf:/etc/nginx/nginx.conf"
